title: Wailuku
description: A lightweight, flexible, and easy-to-use web framework for Dart
baseurl: "/wailuku" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Navigation
nav:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: API Reference
    url: /api-reference
  - title: Contributing
    url: /contributing

# Default layout
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default" 